// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService_Kisen.Data;

#nullable disable

namespace NotificationService_Kisen.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20250426160949_InitAllModels")]
    partial class InitAllModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotificationService_Kisen.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionId");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            RegionId = 1,
                            Name = "Kyiv"
                        },
                        new
                        {
                            RegionId = 2,
                            Name = "Kharkiv"
                        },
                        new
                        {
                            RegionId = 3,
                            Name = "Odesa"
                        },
                        new
                        {
                            RegionId = 4,
                            Name = "Dnipro"
                        },
                        new
                        {
                            RegionId = 5,
                            Name = "Donetsk"
                        },
                        new
                        {
                            RegionId = 6,
                            Name = "Lviv"
                        },
                        new
                        {
                            RegionId = 7,
                            Name = "Zaporizhzhia"
                        },
                        new
                        {
                            RegionId = 8,
                            Name = "Kryvyi Rih"
                        },
                        new
                        {
                            RegionId = 9,
                            Name = "Mykolaiv"
                        },
                        new
                        {
                            RegionId = 10,
                            Name = "Mariupol"
                        },
                        new
                        {
                            RegionId = 11,
                            Name = "Luhansk"
                        },
                        new
                        {
                            RegionId = 12,
                            Name = "Vinnytsia"
                        },
                        new
                        {
                            RegionId = 13,
                            Name = "Sevastopol"
                        },
                        new
                        {
                            RegionId = 14,
                            Name = "Simferopol"
                        },
                        new
                        {
                            RegionId = 15,
                            Name = "Kherson"
                        },
                        new
                        {
                            RegionId = 16,
                            Name = "Poltava"
                        },
                        new
                        {
                            RegionId = 17,
                            Name = "Chernihiv"
                        },
                        new
                        {
                            RegionId = 18,
                            Name = "Cherkasy"
                        },
                        new
                        {
                            RegionId = 19,
                            Name = "Zhytomyr"
                        },
                        new
                        {
                            RegionId = 20,
                            Name = "Sumy"
                        },
                        new
                        {
                            RegionId = 21,
                            Name = "Khmelnytskyi"
                        },
                        new
                        {
                            RegionId = 22,
                            Name = "Chernivtsi"
                        },
                        new
                        {
                            RegionId = 23,
                            Name = "Rivne"
                        },
                        new
                        {
                            RegionId = 24,
                            Name = "Ivano-Frankivsk"
                        },
                        new
                        {
                            RegionId = 25,
                            Name = "Kropyvnytskyi"
                        },
                        new
                        {
                            RegionId = 26,
                            Name = "Kamianske"
                        },
                        new
                        {
                            RegionId = 27,
                            Name = "Lutsk"
                        },
                        new
                        {
                            RegionId = 28,
                            Name = "Kremenchuk"
                        },
                        new
                        {
                            RegionId = 29,
                            Name = "Bila Tserkva"
                        },
                        new
                        {
                            RegionId = 30,
                            Name = "Melitopol"
                        });
                });

            modelBuilder.Entity("NotificationService_Kisen.Models.Subscriber", b =>
                {
                    b.Property<string>("SubscriberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ReceiveNewAlerts")
                        .HasColumnType("bit");

                    b.Property<string>("SubscriberType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubscriberId");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("NotificationService_Kisen.Models.SubscriberRegion", b =>
                {
                    b.Property<string>("SubscriberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("SubscriberId", "RegionId");

                    b.HasIndex("RegionId");

                    b.ToTable("SubscriberRegions");
                });

            modelBuilder.Entity("NotificationService_Kisen.Models.SubscriberRegion", b =>
                {
                    b.HasOne("NotificationService_Kisen.Models.Region", "Region")
                        .WithMany("Subscriptions")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotificationService_Kisen.Models.Subscriber", "Subscriber")
                        .WithMany("Regions")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("NotificationService_Kisen.Models.Region", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("NotificationService_Kisen.Models.Subscriber", b =>
                {
                    b.Navigation("Regions");
                });
#pragma warning restore 612, 618
        }
    }
}
