// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService_Kisen.Data;

#nullable disable

namespace NotificationService_Kisen.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    partial class NotificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotificationService_Kisen.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionId");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            RegionId = 1,
                            Name = "Київ"
                        },
                        new
                        {
                            RegionId = 2,
                            Name = "Харків"
                        },
                        new
                        {
                            RegionId = 3,
                            Name = "Одеса"
                        },
                        new
                        {
                            RegionId = 4,
                            Name = "Дніпро"
                        },
                        new
                        {
                            RegionId = 5,
                            Name = "Донецьк"
                        },
                        new
                        {
                            RegionId = 6,
                            Name = "Львів"
                        },
                        new
                        {
                            RegionId = 7,
                            Name = "Запоріжжя"
                        },
                        new
                        {
                            RegionId = 8,
                            Name = "Кривий Ріг"
                        },
                        new
                        {
                            RegionId = 9,
                            Name = "Миколаїв"
                        },
                        new
                        {
                            RegionId = 10,
                            Name = "Маріуполь"
                        },
                        new
                        {
                            RegionId = 11,
                            Name = "Луганськ"
                        },
                        new
                        {
                            RegionId = 12,
                            Name = "Вінниця"
                        },
                        new
                        {
                            RegionId = 13,
                            Name = "Севастополь"
                        },
                        new
                        {
                            RegionId = 14,
                            Name = "Сімферополь"
                        },
                        new
                        {
                            RegionId = 15,
                            Name = "Херсон"
                        },
                        new
                        {
                            RegionId = 16,
                            Name = "Полтава"
                        },
                        new
                        {
                            RegionId = 17,
                            Name = "Чернігів"
                        },
                        new
                        {
                            RegionId = 18,
                            Name = "Черкаси"
                        },
                        new
                        {
                            RegionId = 19,
                            Name = "Житомир"
                        },
                        new
                        {
                            RegionId = 20,
                            Name = "Суми"
                        },
                        new
                        {
                            RegionId = 21,
                            Name = "Хмельницький"
                        },
                        new
                        {
                            RegionId = 22,
                            Name = "Чернівці"
                        },
                        new
                        {
                            RegionId = 23,
                            Name = "Рівне"
                        },
                        new
                        {
                            RegionId = 24,
                            Name = "Івано-Франківськ"
                        },
                        new
                        {
                            RegionId = 25,
                            Name = "Кропивницький"
                        },
                        new
                        {
                            RegionId = 26,
                            Name = "Кам'янське"
                        },
                        new
                        {
                            RegionId = 27,
                            Name = "Луцьк"
                        },
                        new
                        {
                            RegionId = 28,
                            Name = "Кременчук"
                        },
                        new
                        {
                            RegionId = 29,
                            Name = "Біла Церква"
                        },
                        new
                        {
                            RegionId = 30,
                            Name = "Мелітополь"
                        });
                });

            modelBuilder.Entity("NotificationService_Kisen.Models.Subscriber", b =>
                {
                    b.Property<string>("SubscriberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ReceiveNewAlerts")
                        .HasColumnType("bit");

                    b.Property<string>("SubscriberType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubscriberId");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("NotificationService_Kisen.Models.SubscriberRegion", b =>
                {
                    b.Property<string>("SubscriberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("SubscriberId", "RegionId");

                    b.HasIndex("RegionId");

                    b.ToTable("SubscriberRegions");
                });

            modelBuilder.Entity("NotificationService_Kisen.Models.SubscriberRegion", b =>
                {
                    b.HasOne("NotificationService_Kisen.Models.Region", "Region")
                        .WithMany("Subscriptions")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotificationService_Kisen.Models.Subscriber", "Subscriber")
                        .WithMany("Regions")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("NotificationService_Kisen.Models.Region", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("NotificationService_Kisen.Models.Subscriber", b =>
                {
                    b.Navigation("Regions");
                });
#pragma warning restore 612, 618
        }
    }
}
